import type { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'sonner'

import { halyardDisplay, montserrat } from '@/fonts'
import './globals.css'
import Footer from '@/layouts/footer/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.variable} ${halyardDisplay.variable} ${halyardDisplay.className} antialiased`}
      >
        {children}
        <NextTopLoader
          color='linear-gradient(0deg, #8CC63F 0%, #27AAE1 100%)'
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing='ease'
          speed={200}
          shadow='0 0 10px #8CC63F,0 0 5px #27AAE1'
          template='<div class="bar" role="bar"><div class="peg"></div></div>
    <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
          zIndex={1600}
          showAtBottom={false}
        />
        <Toaster richColors />
        <Footer></Footer>
      </body>
    </html>
  )
}
